#!/usr/bin/env python3
import pathlib, re, html
ROOT = pathlib.Path(__file__).resolve().parents[1]
HEADING_RE = re.compile(r"^(#{1,5})\s+(.+?)\s*$")
NUM_RE = re.compile(r"^(\d+(?:\.\d+)*)\b")
START='<!-- AUTOGENERATED TOC START -->'; END='<!-- AUTOGENERATED TOC END -->'

def slug(s):
    import re
    s=s.lower(); s=re.sub(r"`+",'',s)
    s=re.sub(r"\[([^\]]+)\]\([^)]*\)",r"\1",s)
    s=re.sub(r"[^a-z0-9\-\s\.]+","",s)
    s=re.sub(r"\s+","-",s)
    return s.strip('-')

def anchor_line(text):
    ids=[]; m=NUM_RE.match(text)
    if m:
        ids+=[m.group(1), m.group(1).replace('.',''), m.group(1).split('.')[0]]
    s=slug(text)
    if s: ids.append(s)
    seen=set(); ids=[i for i in ids if not (i in seen or seen.add(i))]
    if not ids: return ''
    return ''.join(f'<a id="{html.escape(i)}"></a>' for i in ids)+"\n"

def toc(headings):
    lines=[START,'\n']
    for level,text in headings:
        if level<2: continue
        indent=max(0,level-2)*2
        m=NUM_RE.match(text); a=m.group(1) if m else slug(text)
        lines.append(' ' * indent + f"- [{text}](#{a})\n")
    lines.append('\n'+END+'\n'); return ''.join(lines)

def process(p):
    t=p.read_text(encoding='utf-8'); lines=t.splitlines(True)
    out=[]; in_code=False; heads=[]; i=0; changed=False
    while i<len(lines):
        L=lines[i]
        if L.strip().startswith('```'):
            in_code=not in_code; out.append(L); i+=1; continue
        if not in_code:
            m=HEADING_RE.match(L)
            if m:
                level=len(m.group(1)); text=m.group(2).strip()
                out.append(L)
                if level>=2: heads.append((level,text))
                nxt=lines[i+1] if i+1<len(lines) else '\n'
                if not nxt.strip().startswith('<a id='):
                    al=anchor_line(text)
                    if al:
                        out.append(al); changed=True
                i+=1; continue
        out.append(L); i+=1
    new=''.join(out)
    if heads:
        tblock=toc(heads)
        import re
        if START in new and END in new:
            new2=re.sub(re.escape(START)+r"[\s\S]*?"+re.escape(END), tblock.strip(), new)
            if new2!=new: changed=True; new=new2
        else:
            m=re.search(r"^#\s+.+$", new, flags=re.M)
            if m:
                pos=m.end(); new=new[:pos]+"\n\n"+tblock+new[pos:]; changed=True
    if changed: p.write_text(new, encoding='utf-8')

if __name__=='__main__':
    for md in (ROOT/'docs').rglob('*.md'):
        process(md)
